apiVersion: apps/v1
kind: Deployment
metadata:
  name: subsonic
  labels:
    app: subsonic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subsonic
  template:
    metadata:
      labels:
        app: subsonic
    spec:
      containers:
      - name: subsonic
        image: mpaganini/alpine-subsonic
        ports:
        - containerPort: 4040
        volumeMounts:
          - name: music
            mountPath: /var/music:ro
          - name: state
            mountPath: /var/subsonic
      volumes:
        - name: music
          hostPath:
            path: /media/sjaoraid/music
        - name: state
          hostPath:
            path: /var/subsonic

---
apiVersion: v1
kind: Service
metadata:
  name: subsonic
spec:
  ports:
    - port: 4040
  selector:
    app: subsonic
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: rstudio
          servicePort: 8787

